### ISSUE TITLE
Use laravel pagination cursor

### ISSUE THREAD

**Issue by developcreativo** [jeffsrepoaccount/laravel-rest-api#1]
Use pagination cursor?

**Comment by jeffsrepoaccount** [comment]
@vdjkelly I'm not 100% sure I understand what you're referring to, but the pagination is actually built on top of [league/fractal](http://fractal.thephpleague.com/) and uses their cursors. My decision for going with cursor-based pagination is because they tend to provide better consistency, especially when real-time data is involved than 'classic' page-based pagination provides.

This repository is also a bit behind of where my current work with REST APIs is, I hope to bring it up to current some time in the semi-near future.

**Comment by developcreativo** [comment]
Sorry for my language I do not speak English very well, what I was referring to was that if your package can use the cursor page as state by seeing in this code from your ApiController @jeffsrepoaccount 

```
    protected function cursor($collection, $perPage, $curCursor)
    {
        $curCursor = ($curCursor && count($collection)) ? $collection->first()->cursor : null; 
        $prevCursor = null;
        $nextCursor = $this->entity->nextPage($collection, $perPage, (string)$curCursor);
        if($curCursor) {
            $prevCursor = $this->entity->previousPage($collection, $perPage, (string)$curCursor);    
        }
        return new Cursor(
            base64_encode($curCursor), 
            $prevCursor ? base64_encode($prevCursor) : null,
            $nextCursor ? base64_encode($nextCursor) : null,
            $collection->count()
        );
    }
```

If this is how to implement it in a controller with its package, some example of how to do it?

**Comment by jeffsrepoaccount** [comment]
@vdjkelly Sorry for the long awaited response, you've probably moved on long ago but since I've finally gotten around to responding I'll go ahead and do so at least for posterity's sake.

The cursor method you mentioned is used internally. It ultimately will get handled [league/fractal](https://github.com/thephpleague/fractal) which this package is built on top of. That cursor method I have is really just looking up what IDs, given the current cursor and the number per page as a parameter, should constitute the previous/next page pointers to pass as parameters into fractal's cursor. You shouldn't have to worry calling it directly.
